{{- range .Values.services }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-secrets
type: Opaque
stringData:
  db.password: {{ $.Values.secrets.dbPasswordSecret | default "password" }}
  jwt.signing.key: {{ $.Values.secrets.jwtSigningKey | default "replace-with-secret" }}
---
{{- end }}

